os: linux
rvm: 2.6.3
arch: amd64           # LXD container based build for OSS only
os: linux             # required for arch different than amd64
dist: focal           # or bionic | xenial with xenial as default
vm:
  size: 2x-large
jobs:
  include:
    - stage: sleep
      script: sleep 30
    - stage: test
      script: sleep 30
      vm:
        size: large
    - stage: deploy
      script: sleep 30
      vm:
        size: medium
notifications:
  email:
    - shairyarbaig@gmail.com
    - shairyarbaig@gmail.com
